
# Autogenerated by mlir-tblgen; don't manually edit.

from ._ods_common import _cext as _ods_cext
from ._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_result_or_op_results as _get_op_result_or_op_results,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Sequence as _Sequence, Union as _Union


from ._transform_ops_gen import _Dialect

@_ods_cext.register_operation(_Dialect)
class ApplyCastAwayVectorLeadingOneDimPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.cast_away_vector_leading_one_dim"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_cast_away_vector_leading_one_dim(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyCastAwayVectorLeadingOneDimPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyDropUnitDimWithShapeCastPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.drop_unit_dims_with_shape_cast"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_drop_unit_dims_with_shape_cast(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyDropUnitDimWithShapeCastPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyFoldArithExtensionPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.fold_arith_extension"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_fold_arith_extension(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyFoldArithExtensionPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyFoldElementwiseToVectorPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.elementwise_to_vector"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_elementwise_to_vector(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyFoldElementwiseToVectorPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyInterleaveToShufflePatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.interleave_to_shuffle"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_interleave_to_shuffle(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyInterleaveToShufflePatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerBitCastPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_bitcast"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_bitcast(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerBitCastPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerBroadcastPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_broadcast"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_broadcast(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerBroadcastPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerContractionPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_contraction"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, lowering_strategy=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if lowering_strategy is not None: attributes["lowering_strategy"] = (lowering_strategy if (
        isinstance(lowering_strategy, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('VectorContractLoweringAttr')) else
          _ods_ir.AttrBuilder.get('VectorContractLoweringAttr')(lowering_strategy, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def lowering_strategy(self):
    return self.operation.attributes["lowering_strategy"]

  @lowering_strategy.setter
  def lowering_strategy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["lowering_strategy"] = value

def apply_patterns_vector_lower_contraction(*, lowering_strategy=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerContractionPatternsOp(lowering_strategy=lowering_strategy, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerCreateMaskPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_create_mask"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_create_mask(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerCreateMaskPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerGatherPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_gather"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_gather(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerGatherPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerInterleavePatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_interleave"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_interleave(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerInterleavePatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerMaskedTransfersPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_masked_transfers"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_masked_transfers(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerMaskedTransfersPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerMasksPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_masks"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_masks(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerMasksPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerMultiReductionPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_multi_reduction"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, lowering_strategy=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if lowering_strategy is not None: attributes["lowering_strategy"] = (lowering_strategy if (
        isinstance(lowering_strategy, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('VectorMultiReductionLoweringAttr')) else
          _ods_ir.AttrBuilder.get('VectorMultiReductionLoweringAttr')(lowering_strategy, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def lowering_strategy(self):
    return self.operation.attributes["lowering_strategy"]

  @lowering_strategy.setter
  def lowering_strategy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["lowering_strategy"] = value

def apply_patterns_vector_lower_multi_reduction(*, lowering_strategy=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerMultiReductionPatternsOp(lowering_strategy=lowering_strategy, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerOuterProductPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_outerproduct"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_outerproduct(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerOuterProductPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerScanPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_scan"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_scan(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerScanPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerShapeCastPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_shape_cast"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_lower_shape_cast(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerShapeCastPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerTransferPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_transfer"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, max_transfer_rank=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if max_transfer_rank is not None: attributes["max_transfer_rank"] = (max_transfer_rank if (
        isinstance(max_transfer_rank, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('I64Attr')) else
          _ods_ir.AttrBuilder.get('I64Attr')(max_transfer_rank, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def max_transfer_rank(self):
    return self.operation.attributes["max_transfer_rank"]

  @max_transfer_rank.setter
  def max_transfer_rank(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["max_transfer_rank"] = value

def apply_patterns_vector_lower_transfer(*, max_transfer_rank=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerTransferPatternsOp(max_transfer_rank=max_transfer_rank, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyLowerTransposePatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.lower_transpose"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, lowering_strategy=None, avx2_lowering_strategy=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if lowering_strategy is not None: attributes["lowering_strategy"] = (lowering_strategy if (
        isinstance(lowering_strategy, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('VectorTransposeLoweringAttr')) else
          _ods_ir.AttrBuilder.get('VectorTransposeLoweringAttr')(lowering_strategy, context=_ods_context))
    if avx2_lowering_strategy is not None: attributes["avx2_lowering_strategy"] = (avx2_lowering_strategy if (
        isinstance(avx2_lowering_strategy, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('BoolAttr')) else
          _ods_ir.AttrBuilder.get('BoolAttr')(avx2_lowering_strategy, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def lowering_strategy(self):
    return self.operation.attributes["lowering_strategy"]

  @lowering_strategy.setter
  def lowering_strategy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["lowering_strategy"] = value

  @builtins.property
  def avx2_lowering_strategy(self):
    return self.operation.attributes["avx2_lowering_strategy"]

  @avx2_lowering_strategy.setter
  def avx2_lowering_strategy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["avx2_lowering_strategy"] = value

def apply_patterns_vector_lower_transpose(*, lowering_strategy=None, avx2_lowering_strategy=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyLowerTransposePatternsOp(lowering_strategy=lowering_strategy, avx2_lowering_strategy=avx2_lowering_strategy, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyMaterializeMasksPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.materialize_masks"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_materialize_masks(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyMaterializeMasksPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyRankReducingSubviewPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.rank_reducing_subview_patterns"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_rank_reducing_subview_patterns(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyRankReducingSubviewPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyRewriteNarrowTypePatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.rewrite_narrow_types"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_rewrite_narrow_types(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyRewriteNarrowTypePatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplySinkVectorPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.sink_ops"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_sink_ops(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplySinkVectorPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplySplitTransferFullPartialPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.split_transfer_full_partial"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, split_transfer_strategy=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if split_transfer_strategy is not None: attributes["split_transfer_strategy"] = (split_transfer_strategy if (
        isinstance(split_transfer_strategy, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('VectorTransferSplitAttr')) else
          _ods_ir.AttrBuilder.get('VectorTransferSplitAttr')(split_transfer_strategy, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def split_transfer_strategy(self):
    return self.operation.attributes["split_transfer_strategy"]

  @split_transfer_strategy.setter
  def split_transfer_strategy(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["split_transfer_strategy"] = value

def apply_patterns_vector_split_transfer_full_partial(*, split_transfer_strategy=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplySplitTransferFullPartialPatternsOp(split_transfer_strategy=split_transfer_strategy, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyTransferPermutationPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.transfer_permutation_patterns"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_transfer_permutation_patterns(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyTransferPermutationPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyTransferToScfPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.transfer_to_scf"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, max_transfer_rank=None, full_unroll=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if max_transfer_rank is not None: attributes["max_transfer_rank"] = (max_transfer_rank if (
        isinstance(max_transfer_rank, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('I64Attr')) else
          _ods_ir.AttrBuilder.get('I64Attr')(max_transfer_rank, context=_ods_context))
    if full_unroll is not None: attributes["full_unroll"] = (full_unroll if (
        isinstance(full_unroll, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('BoolAttr')) else
          _ods_ir.AttrBuilder.get('BoolAttr')(full_unroll, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def max_transfer_rank(self):
    return self.operation.attributes["max_transfer_rank"]

  @max_transfer_rank.setter
  def max_transfer_rank(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["max_transfer_rank"] = value

  @builtins.property
  def full_unroll(self):
    return self.operation.attributes["full_unroll"]

  @full_unroll.setter
  def full_unroll(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["full_unroll"] = value

def apply_patterns_vector_transfer_to_scf(*, max_transfer_rank=None, full_unroll=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyTransferToScfPatternsOp(max_transfer_rank=max_transfer_rank, full_unroll=full_unroll, loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyVectorReductionToContractPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_patterns.vector.reduction_to_contract"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

def apply_patterns_vector_reduction_to_contract(*, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyVectorReductionToContractPatternsOp(loc=loc, ip=ip)

@_ods_cext.register_operation(_Dialect)
class ApplyVectorToLLVMConversionPatternsOp(_ods_ir.OpView):
  OPERATION_NAME = "transform.apply_conversion_patterns.vector.vector_to_llvm"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, reassociate_fp_reductions=None, force_32bit_vector_indices=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    if reassociate_fp_reductions is not None: attributes["reassociate_fp_reductions"] = (reassociate_fp_reductions if (
        isinstance(reassociate_fp_reductions, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('BoolAttr')) else
          _ods_ir.AttrBuilder.get('BoolAttr')(reassociate_fp_reductions, context=_ods_context))
    if force_32bit_vector_indices is not None: attributes["force_32bit_vector_indices"] = (force_32bit_vector_indices if (
        isinstance(force_32bit_vector_indices, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('BoolAttr')) else
          _ods_ir.AttrBuilder.get('BoolAttr')(force_32bit_vector_indices, context=_ods_context))
    _ods_successors = None
    super().__init__(self.OPERATION_NAME, self._ODS_REGIONS, self._ODS_OPERAND_SEGMENTS, self._ODS_RESULT_SEGMENTS, attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip)

  @builtins.property
  def reassociate_fp_reductions(self):
    return self.operation.attributes["reassociate_fp_reductions"]

  @reassociate_fp_reductions.setter
  def reassociate_fp_reductions(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["reassociate_fp_reductions"] = value

  @builtins.property
  def force_32bit_vector_indices(self):
    return self.operation.attributes["force_32bit_vector_indices"]

  @force_32bit_vector_indices.setter
  def force_32bit_vector_indices(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["force_32bit_vector_indices"] = value

def apply_conversion_patterns_vector_vector_to_llvm(*, reassociate_fp_reductions=None, force_32bit_vector_indices=None, loc=None, ip=None) -> _ods_ir.Operation:
  return ApplyVectorToLLVMConversionPatternsOp(reassociate_fp_reductions=reassociate_fp_reductions, force_32bit_vector_indices=force_32bit_vector_indices, loc=loc, ip=ip)
